exclude_patterns:
  - "**/*test.js"
  - "**/*test.jsx"
  - "**/config"
plugins:
  eslint:
    channel: eslint-4
    config:
      extensions:
        - .es6
        - .js
        - .jsx
    enabled: true
